### ISSUE TITLE
[iOS] pitch로 게임 진행하기

### ISSUE THREAD

**Issue by eeeesong** [ehdrhelr/baseball#21]
애니메이션 구현과 별개의 이슈로 다뤄야 할 것 같아서 하나 더 팠습니다!
Combine / Notification 등 객체 간 정보 이동 방식이 좀 더 명확해지고 나서,
game 객체의 정보 변화에 따라 특정 애니메이션을 어떻게 호출시킬 지 논의 + 구현하면 좋을 것 같습니다 :)
(대충 애니메이션 모양새 완성 + PR 수정 끝나면 지식을 합쳐서 구현하면 될 것 같다는 얘기)

--------

### To-do
- [x] pitch 버튼 누를 시 GET 보내기
- [x] 받은 데이터에 따라 모델 값 업데이트
- [x] 모델 업데이트에 따른 animation 연동

**Comment by eeeesong** [comment]
내일 핵심(?)만 빠르게 적용하면 좋을 것 같아서 마이너한 변경 사항들은 미리 반영을 해뒀습니다!
참고로 커밋할 때는 전에 만들어 놓은 #3 이슈를 태그해서... 여기 보이지 않네요ㅎㅎ..

1. endpoint 업데이트 -> 서버 주소 반영 + port 속성 추가 (8080)
2. DataDTO 추가 -> 뭔가..네이밍이 구리긴 한데 마땅히 떠오르는 이름이 없어서...
   - 모든 데이터가 data / error 에 감싸여서 오므로, 아래와 같은 데이터 형식을 하나 추가했습니다.
   - 그리고 viewModel에서 request 시 각각 `DataDTO<[Game]>.self`, `DataDTO<GameDTO>.self`를 타입으로 넘겨주도록 수정했습니다.

```swift
struct DataDTO<T: Decodable>: Decodable {
    var data: T?
    var error: String?
}
```

3. DTO를 최종 형태에 맞게 변형했습니다
   - `teams`, `inning`, `pitch` 에 각각 사소하게 부합하지 않는 부분이 있어서 수정했습니다. (코딩 키, 데이터 형식 등)

--------

내일은 pitch 버튼 누르면 pitch 보내는 부분, 그 결과에 따라 화면에 뿌려주는 부분부터 작성을 하면 될 것 같습니다!

시간이 늦었으니 따로 태그는 하지 않겠습니다!
